### PR TITLE
Issue405 content grid

### PR DESCRIPTION
**Pull request by mvegaca**
Hi @touseefbsb 

I've added on this PR a ContentGrid template refactors on MVVMBasic.
Based on your original proposal, I've moved the template to the WTS 2.1 folder structure based on Platform folders.

News on template
 - Data shown in gr AdaptativeGridView is obtained from SampleDataService.
 - ItemTemplate border removed to allow Fluent Design light discovering in adaptative grid.
 - Removed the reordered animation from default code generation because it is not mandatory and IMO it should not appear on "out of the box" page generation.
 - Added a template to Page Title composition.
 - Added a template to a shared composition.

Review the ContentGrid page generation on [this branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue405-contentGrid) and if you agree I will translate it to other frameworks on next Wednesday.

When I've finished all frameworks templates for c# and vb you will merge this PR and add a new PR to WTS branch.

Thanks for collaborating ;)

### CODE REVIEW

**Comment by mvegaca** [comment]
Don't worry about the number of commits you can see on this PR because it also contains a merge from 2.1 version in WTS.

**Comment by touseefbsb** [comment]
@mvegaca  Thankyou very much for the contribution and let me have a look at it

**Comment by touseefbsb** [comment]
I can see you have also added commanding to the viewmodel which is best way to do things, seems alright to me.

**Comment by touseefbsb** [comment]
@mvegaca  I have merged the pull request, you can continue to add other frameworks when you get time :)

**Pull request merged**
